### ISSUE TITLE
Комментарии по схеме

### ISSUE THREAD

**Issue by kharvd** [Frommi/BotanNET#1]
1. Почему все айдишники bigserial? В 2 миллиарда не уложимся?
1. У одного проекта может быть много групп? Если нет, лучше не делать отдельную таблицу GroupProjects, а занести в Projects поле group_id. Аналогично ProjectTasks.
1. Потенциально можно добавить комменты и вложения к таскам.

**Comment by Frommi** [comment]
1. Заменили на serial.
2. Убрали GroupProjects.
3. Добавили список комментариев к Task'у.
